#!/usr/bin/env ruby

begin
  require 'github_api'
  require 'highline/import'
  require 'rake'
  require 'netrc'
rescue LoadError
  puts "Missing Gems! Install with `gem install github_api highline rake netrc`"
  exit 1
end

RakeFileUtils.verbose_flag = false
include RakeFileUtils

netrc = Netrc.read
username, password = netrc["github.com"]

if username.nil?
  username = ask("Username: ")
  password = ask("Password: ") { |q| q.echo = false }
end

org = File.basename(Dir.pwd)

gh = Github.new({
  basic_auth: "#{username}:#{password}",
  auto_pagination: true,
})

gh.repos.list(org: org).sort_by { |r| r[:name] }.each do |repo|
  if File.exist?(repo[:name])
    puts ">>> Fetching #{org}/#{repo[:name]}"
    Dir.chdir(repo[:name]) do
      sh("git fetch -a")
    end
  else
    puts ">>> Cloning #{org}/#{repo[:name]}"
    sh("git clone #{repo[:clone_url]}")
  end
end
