#!/sbin/runscript
# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

name="hadoop-jobtracker"
command="/opt/hadoop/bin/hadoop"
command_args="--config /opt/hadoop/conf jobtracker"
command_background="true"
start_stop_daemon_args="--user hadoop --group hadoop"
pidfile="/var/run/hadoop/jobtracker.pid"

depend() {
        need net
}
