#!/sbin/runscript
# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

name="hadoop-namenode"

pidfile="/var/run/hadoop/namenode.pid"

command="/opt/hadoop/bin/hadoop"
command_args="--config /opt/hadoop/conf namenode"

command_background="true"

command_user="hadoop"
command_group="hadoop"

depend() {
	need net
}

pre_start() {
	checkpath -d -m 0755 -o hadoop:hadoop /var/run/hadoop
}
