#!/usr/bin/perl -w

use strict;

open(PS, "ps --no-headers --sort start -o pid,etime,cmd --ppid `cat /var/run/crond.pid`|") or die( "open: $!" );

my $wrn_secs = 3600*6;
my $crt_secs = 24*3600;

my $warnings = 0;
my $criticals = 0;
my @output = ();

while (<PS>) {
	s/^\s+//; # remove leading wsp
	my @fields = split(/\s+/);
	$fields[1] =~ /(((\d+)-)?(\d{1,2}):)?(\d{2}):(\d{2})/;
	my ($d,$h,$m,$s) = ($3||0, $4||0, $5||0, $6||0);
	my $sec = $s + (60*($m+60*($h+24*$d)));
	#print "pid ".$fields[0]." d=$d,h=$h,m=$m,s=$s = $sec\n";
	if ($sec > $wrn_secs) {
		push @output, "PID ".$fields[0]." is ".$sec."s old";
		if ($sec >= $crt_secs) {
			$criticals++;
		}
		else {
			$warnings++;
		}
	}
}

close(PS);

if ($criticals > 0 || $warnings > 0) {
	print join(", ", @output)."\n";
	if ($criticals>0) {
		exit 2;
	} else {
		exit 1;
	}
}

print "OK";
exit 0;
