# encoding: utf-8

description "Meta cookbook for basic system services"

maintainer "Benedikt Böhm"
maintainer_email "bb@xnull.de"
license "Apache v2.0"

version "5.0.0"

supports "debian"
supports "gentoo"
supports "mac_os_x"

depends "account"
depends "apt"
depends "baselayout"
depends "bash"
depends "chef"
depends "core_ext"
depends "cron"
depends "ganymed"
depends "git"
depends "homebrew"
depends "htop"
depends "hwraid"
depends "iterm"
depends "java"
depends "lftp"
depends "lib_users"
depends "lxc"
depends "mac"
depends "mdadm"
depends "nagios"
depends "nss"
depends "ntp"
depends "openssl"
depends "portage"
depends "postfix"
depends "python"
depends "shorewall"
depends "smart"
depends "splunk"
depends "ssh"
depends "sudo"
depends "syslog"
depends "systemd"
depends "tmux"
depends "vim"
