description "This cookbook installs and configures the base system"

maintainer "Benedikt Böhm"
maintainer_email "bb@xnull.de"
license "Apache v2.0"

supports "gentoo", ">= 2.0"
supports "mac_os_x", ">= 10.7"

depends "core_ext"
depends "git"
depends "hwraid"
depends "lftp"
depends "mdadm"
depends "munin"
depends "nagios"
depends "ntp"
depends "ohai"
depends "openssl"
depends "portage"
depends "shorewall"
depends "smart"
depends "tmux"
depends "vim"
