#!/bin/bash

source /usr/lib/nagios/plugins/utils.sh

output=$(sudo lib_users)

if [[ -n $output ]]; then
	echo "WARNING - processes use old libraries"
	echo "${output}"
	exit $STATE_WARNING
fi

echo "OK - no stale libraries found"
exit $STATE_OK
