#!/bin/bash

set -e

# force unicode locale
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# commit any changes to /etc
cd /etc
git add -A .
git ci -m 'automatic commit before updateworld' || :

# display news items and mark them as read.
eselect news read new | grep -v '^No news is good news.' || :

# dummy run emerge first, so global updates don't clutter the output.
emerge --info &>/dev/null
eout=$(emerge @world -NDuqvp --color=y)

if [[ "${eout}" != "" ]]; then
	echo "${eout}"
	echo
	read -p "press ENTER to merge packages or CTRL-C to abort ... "
	echo
	emerge @world -NDu
fi

# force latest gcc version
latest_gcc=$(gcc-config -l|tail -n1|awk '{print $2}')
current_gcc=$(gcc-config -c)

if [[ $current_gcc != $latest_gcc ]]; then
	gcc-config ${latest_gcc}
fi

# cleanup unneeded dependencies
emerge --depclean -aq

# first try to resolve preserved-libs with binpkgs. if this fails, the second
# run will pick up remaining libs.
emerge @preserved-rebuild
emerge @preserved-rebuild --usepkg=n --getbinpkg=n

# this fucker needs to be run after every upgrade, since noone can be sure what
# has been broken. dude, srsly - can't we simply have PYTHON_TARGETS?
eselect python update --python2

if [[ $(qlist -Ive dev-lang/python | wc -l) != 1 ]]; then
	python-updater -dmanual -- --usepkg
	python-updater -dmanual -- --usepkg=n --getbinpkg=n
fi

# same crap as with python ...
if [[ $(qlist -Ive dev-lang/perl | wc -l) != 1 ]]; then
	perl-cleaner --all -- --usepkg
	perl-cleaner --all -- --usepkg=n --getbinpkg=n
fi

# run lafilefixer to get rid of fucking annoying libtool archive dependency
# crap. aw man. this is getting worse every day.
emerge -n dev-util/lafilefixer
lafilefixer --justfixit > /dev/null

# finally, after all this crap, run revdep-rebuild to pick up remaining
# packages that have broken lib dependencies.
EMERGE_DEFAULT_OPTS="" revdep-rebuild -q -i -- --quiet-build --with-bdeps=y --binpkg-respect-use=y --usepkg=n --getbinpkg=n

# cleanup unneeded dependencies
emerge --depclean -aq

# update config files
etc-update

# run chef-client to fixup configs overwritten by etc-update
chef-client

exit 0
