#!/bin/bash

IMAGE_FILE="base-current.tar.bz2"
MIRROR="http://www.zentoo.org/downloads/amd64"

source /etc/init.d/functions.sh

if [[ $# -lt 3 ]]; then
	echo "Usage: mkvs <name> <fqdn> [<iface>:]<ip>/<prefix> [<template>] [-- <vserver-build opts>]" >&2
	exit 1
fi

NAME=$1 && shift
FQDN=$1 && shift
INTERFACE=$1 && shift

if [[ -z $1 || "$1" = "--" ]]; then
	TEMPLATE=/vservers/${IMAGE_FILE}
	pushd /vservers >/dev/null
	wget -N ${MIRROR}/${IMAGE_FILE}
	popd >/dev/null
else
	TEMPLATE="$1"
fi

shift

VDIR=/vservers/$NAME
CDIR=/etc/vservers/$NAME

IP=${INTERFACE/\/*}
IP=${IP##*:}
XID=${IP##*.}

vserver $NAME build \
	-m template \
	--context $XID \
	--initstyle gentoo \
	--hostname ${FQDN/.*} \
	--interface $INTERFACE \
	"$@" \
	-- \
	-d gentoo \
	-t $TEMPLATE

echo

# start vserver on boot
echo default > $CDIR/apps/init/mark

# do not use shared portage tree
rm -rf $VDIR/usr/portage
sed -i -e '/^\/usr\/portage \/usr\/portage/d' $CDIR/fstab

# use zentoo.org tree and shared binpkgs
mkdir -p $VDIR/usr/portage/{distfiles,packages}
echo 'SYNC="rsync://rsync.zentoo.org/zentoo-portage"' >> $VDIR/etc/make.conf
echo "/usr/portage/packages /usr/portage/packages none bind,rw 0 0" >> $CDIR/fstab

# add /dev/shm to fstab, so sem_open & friends work
echo "none /dev/shm tmpfs defaults 0 0" >> $CDIR/fstab

# use hosts resolv.conf to make sure we have DNS resolution
cp /etc/resolv.conf $VDIR/etc/resolv.conf

# set proper /etc/hosts entries
echo "127.0.0.1 localhost" > $VDIR/etc/hosts
echo "$IP $FQDN ${FQDN/.*}" >> $VDIR/etc/hosts

# disable kmsg polling in syslog-ng (not allowed in vservers)
if [[ -e $VDIR/etc/syslog-ng/syslog-ng.conf ]]; then
	sed -i -e '/kmsg/d' $VDIR/etc/syslog-ng/syslog-ng.conf
fi

# enable sshd
ln -sf /etc/init.d/sshd $VDIR/etc/runlevels/default/sshd

# remerge openssl to get USE=-bindist
vserver $NAME start
vserver $NAME exec emerge --sync
vserver $NAME exec emerge --oneshot --usepkg=n openssl

# set rootpw to tux
echo "root:tux" | vserver $NAME exec chpasswd 2>/dev/null

einfo ""
einfo "All done. Use 'vserver $NAME enter' to login."
einfo ""
