#!/usr/bin/env ruby

require 'nagios'
require 'set'

Class.new(Nagios::Plugin) do
  def initialize
    super

    @code = 0
    @hosts = []

    @config.options.on('-s', '--scope=NAME',
      'scope name') { |scope| @scope = scope }
    @config.options.on('-C', '--code=INT',
      'status code') { |code| @code = code }
    @config.options.on('-H', '--hosts=HOSTS',
                       'comma separated list of hosts') { |hosts| @hosts = hosts.split(',') }

    @config.parse!
    raise "No scope given" unless @scope
  end

  def warning(_)
    @warning.count.to_f / @services.count.to_f > threshold(:warning).to_f
  end

  def critical(_)
    @critical.count.to_f / @services.count.to_f > threshold(:critical).to_f
  end

  def to_s(_)
    "critical=#{@critical} warning=#{@warning} ok=#{@ok}"
  end

  def measure
    scope = ->(section) { section =~ Regexp.new(@scope, Regexp::MULTILINE) }
    @services = Nagios::Status.new("/var/nagios/status.dat", include_ok: true, scope: scope).items

    if !@hosts.empty?
      @services.select! do |service|
        @hosts.include?(service[:host_name])
      end
    end

    @ok = []
    @warning = []
    @critical = []

    @services.each do |service|
      case service[:current_state]
      when 0
        @ok << service[:host_name]
      when 1
        @warning << service[:host_name]
      else
        @critical << service[:host_name]
      end
    end
  end
end.run!
