#!/bin/sh

# Write a command to the Nagios command file to cause
# it to enable active service checks.  This can be
# referred to as 'active' mode in a redundant monitoring
# environment.

commandfile="/var/nagios/rw/nagios.cmd"
now=`date +%s`

# pipe the command to the command file
/usr/bin/printf "[%lu] STOP_OBSESSING_OVER_SVC_CHECKS\n" $now > $commandfile
/usr/bin/printf "[%lu] STOP_OBSESSING_OVER_HOST_CHECKS\n" $now > $commandfile
