#!/bin/bash

commandfile="/var/nagios/rw/nagios.cmd"
now=`date +%s`

commands="
STOP_OBSESSING_OVER_SVC_CHECKS
STOP_EXECUTING_SVC_CHECKS
DISABLE_NOTIFICATIONS
START_ACCEPTING_PASSIVE_SVC_CHECKS
"

for cmd in ${commands}; do
	/usr/bin/printf "[%lu] ${cmd}\n" ${now} > ${commandfile}
done

rm -f /var/nagios/is_master
