#!/bin/sh

# Write a command to the Nagios command file to cause
# it to disable host and service notifications

commandfile="/var/nagios/rw/nagios.cmd"
now=`date +%s`

# pipe the command to the command file
/usr/bin/printf "[%lu] DISABLE_NOTIFICATIONS\n" $now > $commandfile
