#!/bin/bash

commandfile="/var/nagios/rw/nagios.cmd"
now=`date +%s`

commands="
STOP_ACCEPTING_PASSIVE_SVC_CHECKS
ENABLE_NOTIFICATIONS
START_EXECUTING_SVC_CHECKS
START_OBSESSING_OVER_SVC_CHECKS
"

for cmd in ${commands}; do
	/usr/bin/printf "[%lu] ${cmd}\n" ${now} > ${commandfile}
done

touch /var/nagios/is_master
