#!/sbin/runscript
# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

extra_started_commands="reload"

command="/usr/bin/nrpe"
command_args="-c /etc/nagios/nrpe.cfg --daemon"
start_stop_daemon_args="-u nagios -g nagios"
pidfile="/var/run/nrpe/nrpe.pid"

depend() {
	need net
}

reload() {
	ebegin "Reloading nrpe"
	kill -HUP `cat ${pidfile}` &>/dev/null
	eend $? "Failed to reload nrpe"
}
