#!/bin/bash

# select the correct xcode version
echo ">>> Setting XCode to /Applications/Xcode.app"
sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer || exit 1

# reset homebrew repo
echo ">>> Bootstrapping Homebrew"
sudo rm -rf /usr/local/.git
sudo git clone --bare https://github.com/mxcl/homebrew /usr/local/.git
sudo env GIT_DIR=/usr/local/.git GIT_WORK_TREE=/usr/local git config core.bare false
sudo env GIT_DIR=/usr/local/.git GIT_WORK_TREE=/usr/local git reset --hard master
sudo chown -R $(whoami) /usr/local
sudo chown root /usr/local
sudo chgrp -R admin /usr/local
sudo chmod g+rwx /usr/local

# see rvm requirements
brew update
brew tap homebrew/dupes
brew install bash curl git
brew install autoconf automake apple-gcc42 libtool pkg-config openssl readline libyaml sqlite libxml2 libxslt libksba

# bootstrap rvm/bundler
$(dirname $0)/bootstrap || exit 1
source ~/.rvm/scripts/rvm || exit 1
rvm install $(<.ruby-version) || exit 1
rvm use $(<.ruby-version) || exit 1

# run rake solo
rake solo || exit 1

# install iTerm colors and fonts
curl -s -L https://gist.github.com/raw/1595572/417a3fa36e35ca91d6d23ac961071094c26e5fad/Menlo-Powerline.otf > '/Applications/iTerm.app/Menlo-Powerline.otf'
open '/Applications/iTerm.app/Menlo-Powerline.otf'

# open iTerm
curl -s -L https://raw.github.com/altercation/solarized/master/iterm2-colors-solarized/Solarized%20Dark.itermcolors > '/Applications/iTerm.app/Solarized Dark.itermcolors'
open '/Applications/iTerm.app/Solarized Dark.itermcolors'
