#!/bin/bash

# MacOS does not have realpath ... sigh
CHEF_DIR=$(python -c 'import os,sys;print os.path.realpath(sys.argv[1])' $(dirname $0)/../)

# install rvm
if [[ ! -d ~/.rvm ]]; then
	curl -s https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer -o /tmp/rvm-installer
	chmod +x /tmp/rvm-installer
	/tmp/rvm-installer --version 1.6.5 --user-install --path "${HOME}"/.rvm
	rm -f /tmp/rvm-installer
fi

# load rvm
source ~/.rvm/scripts/rvm

# install chef bundle
rvm rvmrc trust "${CHEF_DIR}"
source "${CHEF_DIR}"/.rvmrc

# prevent epic fail in gentoo
for i in ~/.rvm/rubies/*/lib/ruby/site_ruby; do
	touch "${i}"/auto_gem.rb
done

if ! gem query -i -n ^bundler$ > /dev/null; then
	gem install bundler
fi

pushd ${CHEF_DIR} > /dev/null
bundle install
popd > /dev/null
