#!/bin/bash

KV="3.2.7-zentoo"

pushd /usr/src

rm linux

for i in *; do
	echo "Cleaning ${i} ..."
	[[ $i == linux-${KV} ]] || rm -rf $i
done

ln -snf linux-${KV} linux

pushd linux

wget -q -O .config "https://raw.github.com/zentoo/quickstart/master/profiles/3.2.7-zentoo-generic.kconfig"
make oldconfig

genkernel --oldconfig --symlink kernel

popd
popd
