#!/bin/bash

KV="3.5.1-zentoo"

pushd /usr/src

rm linux

for i in linux-*; do
	if [[ $i != linux-${KV} ]]; then
		echo "Cleaning ${i} ..."
		rm -rf $i
	fi
done

ln -snf linux-${KV} linux

if [[ -e /usr/src/linux/vmlinux ]]; then
	echo "!!! vmlinux exists. skipping ..."
	exit 1
fi

pushd linux

make mrproper

wget -q -O .config "https://raw.github.com/zentoo/quickstart/master/profiles/3.5.1-zentoo-generic.kconfig"

genkernel --oldconfig \
	--install \
	--symlink \
	--no-ramdisk-modules \
	--no-splash \
	--no-keymap \
	--lvm \
	--mdadm \
	all

popd
popd
