#!/bin/bash

set -e

# remove bashrc
rm -rf ~/.bash{rc,_profile} ~/.profile

# remove rvm
rm -rf ~/.rvm ~/.rvmrc

# remove homebrew
if [[ -d /usr/local/Cellar ]]; then
	cd /usr/local
	rm -rf Cellar
	brew prune
	rm -rf Library .git .gitignore bin/brew README.md share/man/man1/brew
	rm -rf ~/Library/Caches/Homebrew
fi

# remove Xcode
if [[ -x /Developer/Library/uninstall-devtools ]]; then
	sudo /Developer/Library/uninstall-devtools --mode=all
fi
