#!/bin/bash

set -e

root_device=$1
mount_dir=$(mktemp -d)

mkdir -p ${mount_dir}

mount ${root_device} ${mount_dir}
mount /dev/vg/usr ${mount_dir}/usr
mount /dev/vg/var ${mount_dir}/var

[[ -e /dev/vg/log ]] && mount /dev/vg/log ${mount_dir}/var/log
[[ -e /dev/vg/opt ]] && mount /dev/vg/opt ${mount_dir}/opt
[[ -e /dev/vg/home ]] && mount /dev/vg/home ${mount_dir}/home

mount --bind /dev ${mount_dir}/dev
mount -t proc proc ${mount_dir}/proc

set +e

chroot ${mount_dir} /bin/bash

umount ${mount_dir}/proc
umount ${mount_dir}/dev
[[ -e /dev/vg/home ]] && umount ${mount_dir}/home
[[ -e /dev/vg/opt ]] && umount ${mount_dir}/opt
[[ -e /dev/vg/log ]] && umount ${mount_dir}/var/log
umount ${mount_dir}/var
umount ${mount_dir}/usr
umount ${mount_dir}
