#!/bin/bash

for vdir in /etc/vservers/*; do
	if [[ ! -d ${vdir} ]]; then
		continue
	fi

	vname=$(basename ${vdir})
	xid=$(<${vdir}/context)

	sed -i -e '/\/usr\/portage /d' ${vdir}/fstab

	vnamespace -e ${xid} -- umount /vservers/${vname}/usr/portage/distfiles
	vnamespace -e ${xid} -- umount /vservers/${vname}/usr/portage/packages
	vnamespace -e ${xid} -- umount /vservers/${vname}/usr/portage

	vnamespace -e ${xid} -- mkdir -p /vservers/${vname}/usr/portage
	vnamespace -e ${xid} -- mkdir -p /vservers/${vname}/usr/portage/distfiles
	vnamespace -e ${xid} -- mkdir -p /vservers/${vname}/usr/portage/packages

	vnamespace -e ${xid} -- mount --bind /usr/portage/distfiles /vservers/${vname}/usr/portage/distfiles
	vnamespace -e ${xid} -- mount --bind /usr/portage/packages /vservers/${vname}/usr/portage/packages
done
