#!/bin/bash

cd ~

# install rvm
curl -s https://rvm.beginrescueend.com/install/rvm -o /tmp/rvm-installer
chmod +x /tmp/rvm-installer
/tmp/rvm-installer --version 1.6.5
rm -f /tmp/rvm-installer

# load rvm
source ~/.rvm/scripts/rvm

# install ruby
rvm install ruby-1.8.7-p302
touch ~/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/site_ruby/auto_gem.rb

# install chef gemset
rvm rvmrc trust ~/chef
cd ~/chef
gem install bundler
bundle install

# setup knife
mkdir -p ~/.chef
sudo knife client -a -n create $(whoami) | tail -n +2 > ~/.chef/client.pem

cat <<EOF > ~/.chef/knife.rb
whoami = %x(whoami).chomp
fqdn = %x(hostname -f).chomp

log_level :info
log_location STDOUT

node_name whoami
client_key "/home/#{whoami}/.chef/client.pem"

chef_server_url "https://#{fqdn}"

cache_type 'BasicFile'
cache_options(:path => "/home/#{whoami}/.chef/checksums")

cookbook_path [
  "/home/#{whoami}/chef/cookbooks",
  "/home/#{whoami}/chef/site-cookbooks"
]
EOF
