description "Basic Linux specific resources"

maintainer "Benedikt Boehm"
maintainer_email "bene@bene.dev.zenops.net"
license "Apache v2.0"

version "1.0.0"

supports "debian"
supports "gentoo"

depends "account"
depends "apt"
depends "baselayout"
depends "chef"
depends "core_ext"
depends "cron"
depends "duply"
depends "ganymed"
depends "homebrew"
depends "hwraid"
depends "java"
depends "lib_users"
depends "libvirt"
depends "mdadm"
depends "nagios"
depends "nss"
depends "ntp"
depends "openssl"
depends "portage"
depends "postfix"
depends "shorewall"
depends "smart"
depends "splunk"
depends "sudo"
depends "syslog"
depends "systemd"
depends "watchdog"
