#!/sbin/runscript

name="PHP FastCGI Process Manager"

slot="php<%= node[:php][:slot] %>"

conffile=${PHP_FPM_CONF:-/etc/php/fpm-${slot}/php-fpm.conf}
pidfile=${PHP_FPM_PID:-/var/run/php-fpm.pid}

command=/usr/lib/${slot}/bin/php-fpm
command_args="-y ${conffile} -g ${pidfile}"

stopsig=QUIT
reloadsig=USR2

depend() {
	need net
	use apache2 lighttpd nginx
}

start_pre() {
	checkpath -q -d -m 0755 -o root:root /var/run/php-fpm
}
