#!/bin/bash

if [[ -z $1 ]]; then
	UNITS=$(systemctl list-units --full --no-legend | awk '{print $1}')
else
	UNITS=$1
fi

result=0

for unit in $UNITS; do
	systemctl -q is-active -- $unit &>/dev/null
	ret=$?

	if [[ $ret -ne 0 ]]; then
		echo "${unit}: $(systemctl status $unit | sed 's/.*Active: //;tn;d;:n'), "
		result=2
	fi
done

if [[ $result -eq 0 ]]; then
	echo "All services up and running"
fi

exit $result
