#!/bin/bash

if [ -z "$1" ]; then
	UNITS="$(systemctl list-units --full --no-legend | awk '{print $1}')"
else
	UNITS="$1"
fi

for unit in $UNITS; do
	if ! systemctl -q is-active -- "$unit"; then
		dead_service+=( "$unit" )
	fi
done

if [ "${#dead_service[@]}" == "0" ]; then
	echo "All services are ok"
	exit 0
else
	for x in "${dead_service[@]}"; do
		if ! output="$(systemctl status "$x" | sed 's/.*Active: \(.*\) (.*\; \(.*\)/\1 \2/;tn;d;:n')"; then
			output="is inactive"
		fi
		stat+=( "$x: $output" )
	done

	for x in "${stat[@]}"; do
		echo -ne " \"$x\"" 
	done

	exit 2
fi
