#!/bin/bash

if [[ $# -lt 1 ]]; then
	echo "Usage: check_systemd <unit> [<pidfile>]"
	echo
	echo "Example: check_systemd sshd.service /var/run/sshd.pid"
	exit -1
fi

UNIT=$1
shift

if [[ $(</proc/1/cmdline) == /usr/bin/systemd* ]]; then
	systemctl -q is-active $UNIT &>/dev/null
	ret=$?

	systemctl status $UNIT | sed 's/.*Active: //;tn;d;:n'

	if [[ $ret -eq 0 ]]; then
		exit 0
	else
		exit 2
	fi
fi

# fallback
$(realpath $(dirname $0))/check_pidfile "$@"
