#!/sbin/runscript

depend() {
	use net
}

start() {
	ebegin "Starting monit for user <%= @user[:name] %>"
	start-stop-daemon --start --quiet \
		--pidfile <%= @pidfile %> \
		--user <%= @user[:name] %> \
		--exec /usr/bin/monit \
		-- \
		-p <%= @pidfile %>
	eend $?
}

stop() {
	ebegin "Stopping monit for user <%= @user[:name] %>"
	start-stop-daemon --stop --quiet \
		--pidfile <%= @pidfile %> \
	eend $?
}
