#!/usr/bin/ruby -w

def config(key)
  %x(git config --get #{key.to_s} 2>/dev/null).chomp
end

def cleanup_stale
  age = config('cleanup.age').to_i
  return unless age > 0

  now = Time.now

  stale = %x(git branch --list | egrep '^\s*[0-9]').split.map(&:chomp).select do |branch|
    mtime = Time.at(%x(git --no-pager show -s --format=%at #{branch}).chomp.to_i)
    now - mtime > age*24*60*60
  end

  if stale.any?
    puts
    puts "The following branches had no activity for #{age} days and have been deleted:"
    puts
    stale.each do |branch|
      rev = %x(git rev-parse #{branch}).chomp
      puts " - #{branch} -> #{rev}"
      %x(git branch -D #{branch})
    end
    puts
  end
end

STDIN.each_line do |line|
  rev_old, rev_new, ref = line.split(" ")

  cleanup_stale
end
