#!/usr/bin/ruby -w

def config(key)
  %x(git config --get hooks.#{key.to_s}).chomp
end

def check_whitespace(rev_old, rev_new, ref)
  return unless config(:whitespace) == "true"

  check_result = `git diff --check #{rev_old} #{rev_new}`

  unless check_result.strip.empty?
    STDERR.puts
    STDERR.puts "Your commits have been rejected by `git diff --check':"
    STDERR.puts
    STDERR.puts check_result
    STDERR.puts
    exit(1)
  end
end

def check_linear_history(rev_old, rev_new, ref)
  return unless config(:linearhistory) == "true"

  merges_introduced = `git rev-list --merges #{rev_old}..#{rev_new}`

  unless merges_introduced.strip.empty?
    STDERR.puts
    STDERR.puts "Refusing push to #{ref}, since it would create non-linear"
    STDERR.puts "history by introducing the following merge commits:"
    STDERR.puts merges_introduced
    STDERR.puts
    exit(1)
  end
end

STDIN.each_line do |line|
  rev_old, rev_new, ref = line.split(" ")

  check_whitespace(rev_old, rev_new, ref)
  check_linear_history(rev_old, rev_new, ref)
end
