#!/usr/bin/env ruby

require 'nagios'
require 'nagios/plugin/jolokia'

module UnderReplicatedPartitions
  def bean
    '"kafka.server":name="UnderReplicatedPartitions",type="ReplicaManager"'
  end

  def attribute
    "Value"
  end

  def critical(m)
    m != 0
  end

  def to_s(m)
    "#{m} partitions under replicated"
  end
end

Nagios::Plugin::Jolokia.run!
